apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: kargo-advanced
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/<username>/kargo-advanced.git
  username: <username>
  password: <password>
